name: ZombieZ
version: '${project.version}'
main: com.rinaorc.zombiez.ZombieZPlugin
api-version: '1.21'
description: Looter-Survivor Zombie Game - Rinaorc Studio
author: Rinaorc Studio
website: https://rinaorc.com

# Dépendances optionnelles
softdepend:
  - PlaceholderAPI
  - Vault
  - Citizens
  - ProtocolLib

# Commandes
commands:
  # Commandes Admin
  zombiez:
    description: Commande d'administration ZombieZ
    usage: /<command> <reload|info|stats|setzone|givexp|givepoints|givegems|setlevel|tp|debug|cache>
    permission: zombiez.admin
    aliases: [zz]
    
  zzitem:
    description: Gestion des items procéduraux
    usage: /<command> <generate|give|compare|crate|stats|debug>
    permission: zombiez.admin.items
    aliases: [zzi, item]
    
  zzzombie:
    description: Gestion des zombies et événements
    usage: /<command> <spawn|horde|bloodmoon|boss|stats|kill|toggle|list|event>
    permission: zombiez.admin.zombies
    aliases: [zzz, zombie]

  zzconsumable:
    description: Gestion des consommables
    usage: /<command> <give|list|giveall>
    permission: zombiez.admin.consumables
    aliases: [zzc, consumable]

  zzevent:
    description: Gestion des événements dynamiques (admin) et téléportation (joueurs)
    usage: /<command> [tp <id>] - Joueurs peuvent voir les events et se téléporter
    # Permission retirée pour permettre /event tp aux joueurs
    # Les sous-commandes admin sont protégées par zombiez.admin.events dans le code
    aliases: [zze, event]

  zzmicro:
    description: Gestion des micro-événements personnels
    usage: /<command> <spawn|list|stop|stats|toggle|records>
    permission: zombiez.admin.microevents
    aliases: [zzm, microevent, micro]

  zzweather:
    description: Gestion du systeme meteo dynamique
    usage: /<command> <set|clear|list|toggle|stats|interval|debug|reload>
    permission: zombiez.admin.weather
    aliases: [zzw, weather, meteo]

  zzclassadmin:
    description: Gestion admin des classes (XP, points, niveau, unlock all)
    usage: /<command> <info|setclass|setlevel|givexp|givepoints|unlockall|reset|resettalents>
    permission: zombiez.admin.class
    aliases: [zzca, classadmin]

  zzjourneyadmin:
    description: Gestion admin du journal (skip, unlockall, reset)
    usage: /<command> <info|skip|unlockall|reset|setchapter|setstep> <joueur>
    permission: zombiez.admin.journey
    aliases: [zzja, journeyadmin]

  awaken:
    description: Gestion du système d'éveils (Awaken) sur les items
    usage: /<command> <debug|give|reroll|list|stats|chances|reload>
    permission: zombiez.admin.awaken
    aliases: [zzawaken, eveil]

  zzworldboss:
    description: Gestion du systeme World Boss (evenements aleatoires)
    usage: /<command> <spawn|list|clear|stats|force|toggle|info>
    permission: zombiez.admin.worldboss
    aliases: [zzwb, worldboss, boss]

  # Commandes Joueur
  spawn:
    description: Téléportation au spawn
    usage: /<command>
    permission: zombiez.spawn
    
  stats:
    description: Affiche vos statistiques
    usage: /<command>
    permission: zombiez.stats
    aliases: [statistiques, stat]
    
  zone:
    description: Informations sur les zones
    usage: /<command> [zone_id|list]
    permission: zombiez.zone
    aliases: [zones]
    
  checkpoint:
    description: Affiche votre checkpoint actuel
    usage: /<command>
    permission: zombiez.checkpoint
    aliases: [cp]
    
  refuge:
    description: Affiche les refuges les plus proches
    usage: /<command>
    permission: zombiez.refuge
    aliases: [refuges, shelter]

  journey:
    description: Journal du Survivant - Système de progression guidée
    usage: /<command> [info|chapter|progress|help]
    permission: zombiez.journey
    aliases: [journal, jour, voyage, j]

  gps:
    description: GPS pour les étapes du Journey avec coordonnées
    usage: /<command> [on|off|info|help]
    permission: zombiez.journey
    aliases: [navigation, nav, guide]

  # Commandes Recyclage
  recycle:
    description: Système de recyclage automatique d'items
    usage: /<command> [toggle|hand|all|stats|preview|help]
    permission: zombiez.recycle
    aliases: [recycler, recyclage, rec]

  # Commandes Forge
  forge:
    description: Système de forge pour améliorer les équipements (+1 à +10)
    usage: /<command> [admin]
    permission: zombiez.forge
    aliases: [forgeron, enhancement, ameliorer]

  # Commandes Économie
  prestige:
    description: Système de prestige
    usage: /<command> [confirm]
    permission: zombiez.prestige

  balance:
    description: Voir votre solde
    usage: /<command>
    permission: zombiez.balance
    aliases: [bal, money, argent]
    
  bank:
    description: Banque personnelle
    usage: /<command> [vault|deposit|withdraw|balance]
    permission: zombiez.bank
    aliases: [banque]

  progression:
    description: Système de progression complet
    usage: /<command> [achievements|skills|missions|battlepass|cosmetics|leaderboard|stats]
    permission: zombiez.progression
    aliases: [prog, bp]

  achievements:
    description: Menu des achievements complet
    usage: /<command>
    permission: zombiez.progression
    aliases: [ach, succes, achievement]

  mission:
    description: Menu des missions journalières et hebdomadaires
    usage: /<command>
    permission: zombiez.progression
    aliases: [missions]

  # Commandes Classes
  class:
    description: Système de classes
    usage: /<command> [select|talents|skills|info|buff|use|mutations|help]
    permission: zombiez.class
    aliases: [classe, c]

  mutations:
    description: Voir les mutations quotidiennes
    usage: /<command>
    permission: zombiez.class
    aliases: [mutation, daily]

  talent:
    description: Gestion des talents de classe
    usage: /<command> [info|branch|help]
    permission: zombiez.class
    aliases: [talents, t]

  # Commandes Pets
  pet:
    description: Système de pets
    usage: /<command> [equip|unequip|list|info|egg|fragments|ability|help]
    permission: zombiez.pet.use
    aliases: [pets, compagnon]

  petadmin:
    description: Administration des pets
    usage: /<command> <give|giveegg|givefragments|setlevel|reset|spawnpet|list|eggs>
    permission: zombiez.pet.admin
    aliases: [zzpet, pa]

# Permissions
permissions:
  # Permission wildcard admin
  zombiez.admin:
    description: Accès à toutes les commandes admin
    default: op
    children:
      zombiez.reload: true
      zombiez.stats.others: true
      zombiez.give: true
      zombiez.teleport: true
      zombiez.debug: true
      zombiez.admin.items: true
      zombiez.admin.zombies: true
      zombiez.admin.consumables: true
      zombiez.admin.events: true
      zombiez.admin.microevents: true
      zombiez.admin.weather: true
      zombiez.admin.class: true
      zombiez.pet.admin: true

  zombiez.admin.items:
    description: Gestion des items procéduraux
    default: op

  zombiez.admin.zombies:
    description: Gestion des zombies et événements
    default: op

  zombiez.admin.consumables:
    description: Gestion des consommables
    default: op

  zombiez.admin.events:
    description: Gestion des événements dynamiques
    default: op

  zombiez.admin.microevents:
    description: Gestion des micro-événements personnels
    default: op

  zombiez.admin.weather:
    description: Gestion du systeme meteo dynamique
    default: op

  zombiez.admin.class:
    description: Gestion admin des classes
    default: op

  zombiez.admin.awaken:
    description: Gestion du système d'éveils
    default: op

  zombiez.pet.admin:
    description: Administration des pets
    default: op

  zombiez.reload:
    description: Recharger la configuration
    default: op

  zombiez.stats.others:
    description: Voir les stats des autres joueurs
    default: op

  zombiez.give:
    description: Donner XP/Points/Gems
    default: op

  zombiez.teleport:
    description: TP vers n'importe quelle zone
    default: op

  zombiez.debug:
    description: Accès au mode debug
    default: op

  # Permissions joueur (par défaut true)
  zombiez.player:
    description: Permissions joueur de base
    default: true
    children:
      zombiez.spawn: true
      zombiez.stats: true
      zombiez.zone: true
      zombiez.checkpoint: true
      zombiez.refuge: true
      zombiez.prestige: true
      zombiez.balance: true
      zombiez.bank: true
      zombiez.progression: true
      zombiez.journey: true
      zombiez.class: true
      zombiez.pet.use: true
      zombiez.recycle: true
      zombiez.forge: true

  zombiez.spawn:
    description: Utiliser /spawn
    default: true

  zombiez.stats:
    description: Voir ses propres stats
    default: true

  zombiez.zone:
    description: Voir les infos des zones
    default: true

  zombiez.checkpoint:
    description: Voir son checkpoint
    default: true

  zombiez.refuge:
    description: Voir les refuges
    default: true

  zombiez.prestige:
    description: Accès au prestige
    default: true

  zombiez.balance:
    description: Voir son solde
    default: true

  zombiez.bank:
    description: Accès à la banque
    default: true

  zombiez.progression:
    description: Accès au système de progression
    default: true

  zombiez.journey:
    description: Accès au journal du survivant
    default: true

  zombiez.class:
    description: Accès au système de classes
    default: true

  zombiez.pet.use:
    description: Accès au système de pets
    default: true

  zombiez.recycle:
    description: Accès au système de recyclage
    default: true

  zombiez.forge:
    description: Accès au système de forge
    default: true

  zombiez.forge.admin:
    description: Administration de la forge
    default: op

  # Permissions VIP
  zombiez.vip.bronze:
    description: Rang VIP Bronze
    default: false

  zombiez.vip.silver:
    description: Rang VIP Argent
    default: false

  zombiez.vip.gold:
    description: Rang VIP Or
    default: false

  zombiez.vip.diamond:
    description: Rang VIP Diamant
    default: false

  zombiez.vip.eternal:
    description: Rang VIP Éternel
    default: false
